apiVersion: apps/v1
kind: Deployment
metadata:
  name: artifact-repo
  namespace: devops-tools
  labels:
    app: artifact-repo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artifact-repo
  template:
    metadata:
      labels:
        app: artifact-repo
    spec:
      containers:
        - name: artifact-repo
          image: "registry:3.1.1"
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
