apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-runner
  namespace: devops-tools
  labels:
    app: cicd-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-runner
  template:
    metadata:
      labels:
        app: cicd-runner
    spec:
      containers:
        - name: cicd-runner
          image: "gitlab/gitlab-runner:v19.1.1"
          env:
            - name: CI_SERVER_URL
              value: "http://source-control.devops-tools.svc.cluster.local"
            - name: REGISTRATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gitlab-runner-secret
                  key: registration-token
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
