apiVersion: v1
kind: Service
metadata:
  name: directory-services
  namespace: devops-tools
spec:
  selector:
    app: directory-services
  ports:
    - port: 389
      targetPort: 389
  type: NodePort
