apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring
  namespace: {{ .Values.namespace }}
  labels:
    app: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring
  template:
    metadata:
      labels:
        app: monitoring
    spec:
      containers:
        - name: monitoring
          image: "{{ .Values.monitoring.image.repository }}:{{ .Values.monitoring.image.tag }}"
          ports:
            - containerPort: {{ .Values.monitoring.containerPort }}
          resources:
            requests:
              cpu: {{ .Values.monitoring.resources.requests.cpu }}
              memory: {{ .Values.monitoring.resources.requests.memory }}
            limits:
              cpu: {{ .Values.monitoring.resources.limits.cpu }}
              memory: {{ .Values.monitoring.resources.limits.memory }}
