apiVersion: v1
kind: Service
metadata:
  name: source-control
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: source-control
  ports:
    - port: {{ .Values.sourceControl.servicePort }}
      targetPort: {{ .Values.sourceControl.containerPort }}
  type: NodePort
